version: "3"
services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_MCP_CLIENTS=izin-mcp
      - N8N_MCP_IZIN_MCP_TYPE=stdio
      - N8N_MCP_IZIN_MCP_COMMAND=/usr/local/bin/python /app/izin-mcp.py
      - N8N_MCP_IZIN_MCP_WORKING_DIR=/app
    volumes:
      - ./:/app
    networks:
      - mcp-network
    depends_on:
      - mcp

  mcp:
    build: .
    environment:
      - DB_PATH=/app/personel.db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
